config/routes.rb
Rails.application.routes.draw do

  root 'voters#index'
  resources :voters, except: [:new]

end

app/models/voter.rb
class Voter < ActiveRecord::Base

  validates_presence_of :first_name, :last_name, :city, :state, :zip, message: "This field is required"
  validates :zip, numericality: { only_integer: true, message: " Must be a valid 5 digit zip code." }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController


  def index
    @voters = Voter.all.order(:id).paginate(:page => params[:page], :per_page => 10)
    @voter = Voter.new
  end

  def create
    @voter = Voter.new(voter_params)
    if @voter.save
      render json: @voter
    else
      render :status => 400, :json => @voter.errors.to_json
    end
  end

  def show
    @voter = Voter.find(params[:id])
    render json: @voter
  end

  def update
    @voter = Voter.find(params[:id])
    if @voter.update(voter_params)
      render json: @voter
    else
      render :status => 400, :json => @voter.errors.to_json
    end
  end

  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy
    redirect_to root_path
  end

  private

  def voter_params
    params.permit(:first_name, :last_name, :address, :city, :state, :zip)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper


  def model_fields
    # which fields to display and sort by
    [:first_name, :last_name, :address, :city, :state, :zip]
  end

  def display_search_results(objects)
    objects.each_with_object('') do |object, string|
      string << content_tag(:tr, display_search_results_row(mod_fields, object))
    end
  end

  def display_search_results_row(object)
    model_fields.each_with_object('') do |field, string|
      string << content_tag(:td, object.send(field))
    end
    .html_safe
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Election</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Latest compiled and minified Fontawesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>

  <header>
      <div class="container">
          <div class="row">
              <div class="col-md-12">
                  <a href="/"><h3>Voter Registration</h3></a>
              </div>
          </div>
      </div>
  </header>

<%= yield %>

  <footer>
      <div class="container">
          <div class="row">
              <div class="col-md-12">

              </div>
          </div>
      </div>
  </footer>

</body>
</html>

app/views/voters/index.html.erb
<div class="content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Currently Registered Voters
            <button type="button" id="new-voter" class="btn btn-info btn-sm pull-right" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus-circle"> Add New Voter</i></button>
          </div>
          <div class="panel-body">

            <div class="table-responsive">
              <table class="table table-bordered table-hover">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>First Name #</th>
                    <th>Last Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip Code</th>
                    <th>Options</th>
                  </tr>
                </thead>
                <tbody>
                  <% @voters.each do |voter| %>
                  <%#= link_to(content_tag(:tr, display_search_results_row(voter)), edit_voter_path(voter)) %>
                    <tr>
                      <td><%= voter.id %></td>
                      <td><%= voter.first_name %></td>
                      <td><%= voter.last_name %></td>
                      <td><%= voter.address %></td>
                      <td><%= voter.city %></td>
                      <td><%= voter.state %></td>
                      <td><%= voter.zip %></td>
                      <td><a href="#" class="edit" id="<%= voter.id %>">Edit</a> / <%=link_to("Delete", voter_path(voter), method: :delete) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div><!-- End Table-Responsive  -->

          </div><!-- End Panel Body  -->

          <div class="panel-footer">
            <%= will_paginate @voters %>
          </div>

        </div><!-- End Panel  -->
      </div><!-- End Col -->
    </div><!-- End Row -->
  </div><!-- End Container -->
</div><!-- End Content-Wrapper -->


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add New Voter</h4>
      </div>

      <div class="modal-body">
        <%= form_for @voter, class:"form-horizontal", action:"voters" do |f| %>
          <div class="box-body">
            <div class="row">

              <div class="form-group">
                <%= f.label 'First Name:', class:'col-sm-2 control-label' %>
                <div class="col-sm-4" id="first_name_div">
                  <%= f.text_field :first_name, class:"form-control", id:"first_name", name:"first_name", placeholder:"First Name" %>
                </div>
                <%= f.label 'Last Name:', class:'col-sm-2 control-label' %>
                <div class="col-sm-4" id="last_name_div">
                  <%= f.text_field :last_name, class:"form-control", id:"last_name", name:"last_name", placeholder:"Last Name" %>
                </div>
              </div><!-- /.form-group -->
            </div><!-- /.row -->

            <div class="row">
              <div class="form-group">
                <%= f.label 'Address:', class:'col-sm-2 control-label' %>
                <div class="col-sm-10" id="address_div">
                  <%= f.text_field :address, class:"form-control", id:"address", name:"address", placeholder:"Address" %>
                </div>
              </div><!-- /.form-group -->
            </div><!-- /.row -->

            <div class="row">
              <div class="form-group">
                <%= f.label 'City:', class:'col-sm-2 control-label' %>
                <div class="col-sm-6" id="city_div">
                  <%= f.text_field :city, class:"form-control", id:"city", name:"city", placeholder:"City" %>
                </div>

                <%= f.label 'State:', class:'col-sm-2 control-label' %>
                <div class="col-sm-2" id="state_div">
                  <%= f.text_field :state, class:"form-control", id:"state", name:"state", placeholder:"State" %>
                </div>
              </div><!-- /.form-group -->
            </div><!-- /.row -->

            <div class="row">
              <div class="form-group">
                <%= f.label 'Zip:', class:'col-sm-2 control-label' %>
                <div class="col-sm-3" id="zip_div">
                  <%= f.number_field :zip, class:"form-control", id:"zip", name:"zip", placeholder:"Zip" %>
                </div>
              </div><!-- /.form-group -->
            </div><!-- /.row -->

          </div><!-- /.box-body -->
        </div><!-- /.modal-body -->

        <div class="modal-footer">
          <%= f.submit 'Clear', type:'reset', :class =>"btn btn-default" %>
          <%= f.submit 'Submit', class:"btn btn-info pull-right" %>
        </div>
      <% end %>

    </div><!-- End Modal Content  -->
  </div><!-- End Modal Dialog -->
</div> <!-- End Modal  -->